language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env: RUN_TESTS="NO" POD_LINT="YES"
    - os: osx
      osx_image: xcode8
      env: RUN_TESTS="YES" POD_LINT="NO"
    - os: linux
      sudo: required
      dist: trusty
      env: RUN_TESTS="YES" POD_LINT="NO"

script:
  - if [[ $POD_LINT == "YES" ]]; then
      gem install cocoapods && pod repo update && pod lib lint --allow-warnings;
    fi
  - if [[ $RUN_TESTS == "YES" ]]; then
      eval Scripts/ci.sh;
    fi

after_success:
  - if [[ $RUN_TESTS == "YES" ]]; then
      eval Scripts/coverage.sh;
    fi
